---
title: "week5-discussion"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(sf)
library(terra)
library(spData)
library(spDataLarge)
```

```{r}
# Load raster data representing grain sizes with the three classes clay, silt and sand
grain <- terra::rast(system.file("raster/grain.tif", package = "spData"))
```

```{r}
# Load in data set 
nz_height <- spData::nz_height

# filter to aboce 3100
nzheight_3100 <- nz_height %>%
  filter(elevation > 3100)

# Create template raster
nz_template <- rast(ext(nzheight_3100),
                    resolution = 3000,
                    crs = crs(nzheight_3100))
```

```{r}
# Convert vector points to raster data
nz_raster <- rasterize(nzheight_3100, nz_template, field = 'elevation', fun = 'length')

plot(nz_raster, main = "Number of Elevation Points > 3100 in Each Grid Cell")
plot(st_geometry(nzheight_3100), add = TRUE)
```

```{r}
# function "max" returns maximum elevation value per cell
nz_raster2 <- rasterize(nzheight_3100, nz_template, field = "elevation", fun = max)

plot(nz_raster2, main = "Maximum Elevation in Each Grid Cell ")
plot(st_geometry(nzheight_3100), add = TRUE)
```

```{r}
# Reduce the resolution by combining 2 cells in each direction into larger cells
# Sum the values of all cells for the resulting elevation value
nz_raster_low <- aggregate(nz_raster, fact = 2, fun = sum, na.rm = TRUE)

# Convert the new raster's resolution back to the 3kmx3km resolution of original raster
nz_resample <- resample(nz_raster_low, nz_raster)

plots <- c(nz_raster, nz_resample)
labs <- c("Original 6 x 6 km", "Resample 6 x 6 km")
plot(plots, main = labs)
```

```{r}
plot(nz_raster_low, main = "Resample 3 x 3 km")
```

```{r}
# Convert raster data to polygon vector data
grain_poly <- as.polygons(grain) %>% 
  st_as_sf()

plot(grain, main = "Grain (Raster)")
```

